[workspace]
members = ["perro_api",
    "perro_app", "perro_cli", "perro_compiler", "perro_core", "perro_dev_runner", "perro_graphics", "perro_ids", "perro_io", "perro_modules", "perro_project", "perro_render_bridge", "perro_runtime", "perro_scene", "perro_scripting", "perro_variant",
]

resolver = "3"

[patch.crates-io]
perro_core = {path = "perro_core"}
perro_scene = {path = "perro_scene"}
perro_ids = {path = "perro_ids"}
perro_io = {path = "perro_io"}
perro_api = {path = "perro_api"}
perro_scripting = {path = "perro_scripting"}
perro_variant = {path="perro_variant"}
perro_runtime = {path="perro_runtime"}
perro_modules = {path="perro_modules"}
perro_project = {path="perro_project"}
perro_render_bridge = {path="perro_render_bridge"}
perro_graphics = {path="perro_graphics"}
perro_app = {path="perro_app"}
perro_cli = {path="perro_cli"}
perro_compiler = {path="perro_compiler"}
perro_dev_runner = {path="perro_dev_runner"}

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
incremental = true
debug = false
debug-assertions = false
overflow-checks = false
