[workspace]
members = ["perro_context",
    "perro_app", "perro_cli", "perro_compiler", "perro_core", "perro_dev_runner", "perro_graphics", "perro_ids", "perro_io", "perro_modules", "perro_project", "perro_render_bridge", "perro_runtime", "perro_scene", "perro_scripting", "perro_scripting_macros", "perro_static_pipeline", "perro_variant",
]

resolver = "3"

[patch.crates-io]
perro_core = {path = "perro_core"}
perro_scene = {path = "perro_scene"}
perro_ids = {path = "perro_ids"}
perro_io = {path = "perro_io"}
perro_context = {path = "perro_context"}
perro_scripting = {path = "perro_scripting"}
perro_scripting_macros = {path = "perro_scripting_macros"}
perro_variant = {path="perro_variant"}
perro_runtime = {path="perro_runtime"}
perro_modules = {path="perro_modules"}
perro_project = {path="perro_project"}
perro_render_bridge = {path="perro_render_bridge"}
perro_graphics = {path="perro_graphics"}
perro_app = {path="perro_app"}
perro_cli = {path="perro_cli"}
perro_compiler = {path="perro_compiler"}
perro_dev_runner = {path="perro_dev_runner"}
perro_static_pipeline = {path="perro_static_pipeline"}

[profile.release]
opt-level = 2
lto = "none"
codegen-units = 64
panic = "abort"
strip = "symbols"
incremental = true
debug = false
debug-assertions = false
overflow-checks = false
