[scripts.scripts_editor_pup]
src = "res://scripts/editor.pup"
lang = "pup"
id = "scripts_editor_pup"

[[scripts.scripts_editor_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 66

[[scripts.scripts_editor_pup.lines]]
s_start = 31
s_end = 31
g_start = 66
g_end = 77

[[scripts.scripts_editor_pup.lines]]
s_start = 71
s_end = 71
g_start = 77
g_end = 81

[scripts.scripts_editor_pup.names]
__t_two_d_Pressed = "two_d_Pressed"
__t_file_Pressed = "file_Pressed"
