[scripts.ui_pup]
src = "res://ui.pup"
lang = "pup"
id = "ui_pup"

[[scripts.ui_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 72

[[scripts.ui_pup.lines]]
s_start = 31
s_end = 31
g_start = 72
g_end = 83

[[scripts.ui_pup.lines]]
s_start = 71
s_end = 71
g_start = 83
g_end = 87

[[scripts.ui_pup.lines]]
s_start = 121
s_end = 121
g_start = 87
g_end = 91

[[scripts.ui_pup.lines]]
s_start = 181
s_end = 181
g_start = 91
g_end = 95

[scripts.ui_pup.names]
__t_bob_NotHovered = "bob_NotHovered"
__t_bob_Pressed = "bob_Pressed"
__t_bob_Hovered = "bob_Hovered"
__t_bob_Released = "bob_Released"
