[scripts.ui_pup]
src = "res://ui.pup"
lang = "pup"
id = "ui_pup"

[[scripts.ui_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 65

[[scripts.ui_pup.lines]]
s_start = 31
s_end = 31
g_start = 65
g_end = 76

[scripts.ui_pup.names]
__t_bob_Pressed = "bob_Pressed"
