[scripts.ui_pup]
src = "res://ui.pup"
lang = "pup"
id = "ui_pup"

[[scripts.ui_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 69

[[scripts.ui_pup.lines]]
s_start = 31
s_end = 31
g_start = 69
g_end = 80

[[scripts.ui_pup.lines]]
s_start = 71
s_end = 71
g_start = 80
g_end = 84

[scripts.ui_pup.names]
__t_bob_Pressed = "bob_Pressed"
__t_bob2_Pressed = "bob2_Pressed"
