[target.x86_64-unknown-linux-gnu]   # Linux
linker = "rust-lld"

[target.x86_64-pc-windows-msvc]     # Windows (MSVC toolchain)
linker = "rust-lld"

[target.x86_64-apple-darwin]        # macOS
linker = "rust-lld"