[project]
name = "Perro Engine"
main_scene = "res://editor.scn"
icon = "res://perro-logo.png"
version="0.1.0"

[meta]
toolchain = "1.90.0"

[performance]
target_fps = 120
xps = 60

[root]
script = "res://scripts/root.rs"

