[dependencies]
perro_context = "0.1.0"
perro_core = "0.1.0"
perro_ids = "0.1.0"
perro_modules = "0.1.0"
perro_runtime = "0.1.0"
perro_scripting = "0.1.0"
perro_variant = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[lints.rust.unexpected_cfgs]
check-cfg = ["cfg(rust_analyzer)"]
level = "warn"

[package]
edition = "2024"
name = "scripts"
version = "0.1.0"

[profile.dev]
codegen-units = 256
debug = false
incremental = true
lto = false
opt-level = 0
overflow-checks = false
panic = "abort"
strip = "none"

[profile.dev.package."*"]
codegen-units = 64
debug = false
incremental = true
opt-level = 2
overflow-checks = false
strip = "none"

[workspace]

[patch.crates-io]
perro_context = { path = "../../../../perro_context" }
perro_core = { path = "../../../../perro_core" }
perro_ids = { path = "../../../../perro_ids" }
perro_io = { path = "../../../../perro_io" }
perro_modules = { path = "../../../../perro_modules" }
perro_project = { path = "../../../../perro_project" }
perro_render_bridge = { path = "../../../../perro_render_bridge" }
perro_runtime = { path = "../../../../perro_runtime" }
perro_scene = { path = "../../../../perro_scene" }
perro_scripting = { path = "../../../../perro_scripting" }
perro_scripting_macros = { path = "../../../../perro_scripting_macros" }
perro_variant = { path = "../../../../perro_variant" }
