[scripts.test_engine_structs_pup]
src = "res://test_engine_structs.pup"
lang = "pup"
id = "test_engine_structs_pup"

[[scripts.test_engine_structs_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 78

[[scripts.test_engine_structs_pup.lines]]
s_start = 31
s_end = 31
g_start = 78
g_end = 83

[[scripts.test_engine_structs_pup.lines]]
s_start = 71
s_end = 71
g_start = 83
g_end = 90

[scripts.test_engine_structs_pup.names]
__t_test_constructors = "test_constructors"
__t_test_nested_access = "test_nested_access"
__t_test_variable_access = "test_variable_access"

[scripts.col_pup]
src = "res://col.pup"
lang = "pup"
id = "col_pup"

[[scripts.col_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 72

[[scripts.col_pup.lines]]
s_start = 31
s_end = 31
g_start = 72
g_end = 78

[scripts.col_pup.names]
s_id = "s"

[scripts.p2_pup]
src = "res://p2.pup"
lang = "pup"
id = "p2_pup"

[[scripts.p2_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 69

[scripts.p2_pup.names]

[scripts.shape_pup]
src = "res://shape.pup"
lang = "pup"
id = "shape_pup"

[[scripts.shape_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 68

[scripts.shape_pup.names]

[scripts.player_pup]
src = "res://player.pup"
lang = "pup"
id = "player_pup"

[[scripts.player_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 128

[[scripts.player_pup.lines]]
s_start = 31
s_end = 31
g_start = 128
g_end = 133

[[scripts.player_pup.lines]]
s_start = 71
s_end = 71
g_start = 133
g_end = 145

[[scripts.player_pup.lines]]
s_start = 121
s_end = 121
g_start = 145
g_end = 173

[[scripts.player_pup.lines]]
s_start = 181
s_end = 181
g_start = 173
g_end = 185

[scripts.player_pup.names]
__t_test_b = "test_b"
__t_Cabbage = "Cabbage"
__t_test_var = "test_var"
__t_test = "test"
__t_cab = "cab"
tex_id = "tex"
__t_Deadzone_AreaEntered = "Deadzone_AreaEntered"
__t_time = "time"
__t_Deadzone_AreaExited = "Deadzone_AreaExited"

[scripts.camera_pup]
src = "res://camera.pup"
lang = "pup"
id = "camera_pup"

[[scripts.camera_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 88

[scripts.camera_pup.names]
__t_speed = "speed"

[scripts.root_pup]
src = "res://root.pup"
lang = "pup"
id = "root_pup"

[[scripts.root_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 67

[scripts.root_pup.names]
