[scripts.camera_pup]
src = "res://camera.pup"
lang = "pup"
id = "camera_pup"

[[scripts.camera_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 88

[scripts.camera_pup.names]
__t_speed = "speed"

[scripts.player_pup]
src = "res://player.pup"
lang = "pup"
id = "player_pup"

[[scripts.player_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 124

[[scripts.player_pup.lines]]
s_start = 31
s_end = 31
g_start = 124
g_end = 129

[[scripts.player_pup.lines]]
s_start = 71
s_end = 71
g_start = 129
g_end = 142

[[scripts.player_pup.lines]]
s_start = 121
s_end = 121
g_start = 142
g_end = 188

[[scripts.player_pup.lines]]
s_start = 181
s_end = 181
g_start = 188
g_end = 200

[scripts.player_pup.names]
__t_test_var = "test_var"
__t_test_b = "test_b"
__t_cab = "cab"
__t_test = "test"
__t_time = "time"
tex_id = "tex"
__t_Deadzone_AreaExited = "Deadzone_AreaExited"
__t_Deadzone_AreaEntered = "Deadzone_AreaEntered"
__t_Cabbage = "Cabbage"

[scripts.col_pup]
src = "res://col.pup"
lang = "pup"
id = "col_pup"

[[scripts.col_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 72

[[scripts.col_pup.lines]]
s_start = 31
s_end = 31
g_start = 72
g_end = 78

[scripts.col_pup.names]
s_id = "s"

[scripts.p2_pup]
src = "res://p2.pup"
lang = "pup"
id = "p2_pup"

[[scripts.p2_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 69

[scripts.p2_pup.names]

[scripts.test_engine_structs_pup]
src = "res://test_engine_structs.pup"
lang = "pup"
id = "test_engine_structs_pup"

[[scripts.test_engine_structs_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 78

[[scripts.test_engine_structs_pup.lines]]
s_start = 31
s_end = 31
g_start = 78
g_end = 83

[[scripts.test_engine_structs_pup.lines]]
s_start = 71
s_end = 71
g_start = 83
g_end = 90

[scripts.test_engine_structs_pup.names]
__t_test_nested_access = "test_nested_access"
__t_test_constructors = "test_constructors"
__t_test_variable_access = "test_variable_access"

[scripts.root_pup]
src = "res://root.pup"
lang = "pup"
id = "root_pup"

[[scripts.root_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 70

[[scripts.root_pup.lines]]
s_start = 31
s_end = 31
g_start = 70
g_end = 81

[scripts.root_pup.names]
__t_cabbage = "cabbage"
__t_gas = "gas"

[scripts.glob_test_pup]
src = "res://glob_test.pup"
lang = "pup"
id = "glob_test_pup"

[[scripts.glob_test_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 71

[scripts.glob_test_pup.names]
__t_b = "b"

[scripts.shape_pup]
src = "res://shape.pup"
lang = "pup"
id = "shape_pup"

[[scripts.shape_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 68

[scripts.shape_pup.names]

[scripts.global2_pup]
src = "res://global2.pup"
lang = "pup"
id = "global2_pup"

[[scripts.global2_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 71

[scripts.global2_pup.names]
__t_a = "a"
