[workspace]

[package]
name = "Fart"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
perro_core = { path = "../../perro_core" }
scripts = { path = "../scripts" }
uuid = { version = "1.4", features = ["serde", "v4"] }
indexmap = { version = "1.9", features = ["serde"] }
once_cell = "1.19"
phf = { version = "0.13.1", features = ["macros"] }

[build-dependencies]
toml = "0.8"
embed-resource = "2.4"
image = "0.24"
ico = "0.3"
chrono = "0.4"
resvg = "0.44"

[[bin]]
name = "Fart"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
strip = "symbols"

[profile.release.package."*"]
opt-level = 3
debug = false
overflow-checks = false

[target.'cfg(windows)']
rustflags = ["-C", "link-args=/SUBSYSTEM:WINDOWS"]
