[scripts.threed_pup]
src = "res://threed.pup"
lang = "pup"
id = "threed_pup"

[[scripts.threed_pup.lines]]
s_start = 1
s_end = 1
g_start = 1
g_end = 106

[[scripts.threed_pup.lines]]
s_start = 31
s_end = 31
g_start = 106
g_end = 115

[[scripts.threed_pup.lines]]
s_start = 71
s_end = 71
g_start = 115
g_end = 186

[[scripts.threed_pup.lines]]
s_start = 121
s_end = 121
g_start = 186
g_end = 190

[[scripts.threed_pup.lines]]
s_start = 181
s_end = 181
g_start = 190
g_end = 204

[scripts.threed_pup.names]
__t___timer = "__timer"
__t_log_local = "log_local"
__t_log_global = "log_global"
__t_apply_step = "apply_step"
__t___step = "__step"
