[project]
name = "Perro Test Project"
main_scene = "res://main.scn"
icon = "res://perro-logo.png"
version="1.0.0"

[graphics]
virtual_width = 1920
virtual_height = 1080
msaa = "on"

[performance]
fps_cap = 120
xps = 60

[input]
# Example input mappings - actions can have multiple input sources
jump = ["Space", "Up", "MouseLeft"]
fire = ["MouseLeft", "KeyF"]
move_left = ["Left", "KeyA"]
move_right = ["Right", "KeyD"]
move_up = ["Up", "KeyW"]
move_down = ["Down", "KeyS"]
