[workspace]

[package]
name = "scripts"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
perro_core = { path = "../../../../perro_core" }
serde = { version = "1.0", features = ["derive","rc"] }
serde_json = "1.0"
rust_decimal = { version = "1.36", features = ["serde"] }
num-bigint = { version = "0.4", features = ["serde"] }
smallvec = "1.11"
once_cell = "1.19"
phf = { version = "0.13.1", features = ["macros"] }
toml = "0.8"
regex = "1"

[profile.dev]
opt-level = 2
incremental = true
codegen-units = 256
lto = false
debug = false
strip = "none"
overflow-checks = false
panic = "abort"
